#!/bin/sh

export WMRC_DEPENDENCIES='sudo ddcutil xset'
export _module

WMRC_BACKLIGHT_DEFAULT="${WMRC_BACKLIGHT_DEFAULT:-100}"
WMRC_BACKLIGHT_STEP="${WMRC_BACKLIGHT_STEP:-10}"

internal_vendor="$(find /sys/class/backlight/ -mindepth 1 -maxdepth 1 -printf '%P' | head -n 1)"
internal_file="/sys/class/backlight/$internal_vendor/brightness"
internal_file_max="/sys/class/backlight/$internal_vendor/max_brightness"
external_file="/tmp/wmrc::$(echo "$_module" | sed 's,/,::,g')@$(whoami)${DISPLAY}.brightness"

init() {
    if lsmod | grep -q i2c_dev; then
        info "Already loaded I2C kernel module"
    elif sudo modprobe i2c-dev; then
        info "Loaded I2C kernel module"
    else
        error "Unable to load I2C kernel module"
        return 1
    fi
    if has_monitor internal; then
        info 'Detected internal monitor' "$internal_vendor"
    fi
    if detect_external external; then
        info 'Detected external monitor'
        ddcutil_read
    else
        rm -f "$external_file"
    fi
}

has_monitor() {
    _file="$(eval "$(printf 'echo $%s_file' "${1:-internal}")")"
    if [ -f "$_file" ]; then
        return 0
    else
        return 1
    fi
}

detect_external() {
    if ddcutil detect | grep -q '^Display'; then
        return 0
    else
        return 1
    fi
}

set_to() {
    if [ "$1" != 'internal' ] && [ "$1" != 'external' ]; then
        _value="${1:-$WMRC_BACKLIGHT_DEFAULT}"
        shift 1 2>/dev/null
    else
        _value="$WMRC_BACKLIGHT_DEFAULT"
    fi
    if has_monitor internal && [ "$1" != 'external' ]; then
        _max="$(cat "$internal_file_max")"
        _value="$((_value*_max/100))"
        _internal="$((_value<_max?_value:_max))"
        _internal="$((_value>0?_value:0))"
        echo "$_internal" | sudo tee "$internal_file" >/dev/null
        info 'Set internal backlight' "$_internal"
    fi
    if has_monitor external && [ "$1" != 'internal' ]; then
        if ddcutil_write "$_value"; then
		# ovde fali _value do 100
            info 'Set external backlight' "$_value"
        else
            error 'Failed to set external backlight'
        fi
    fi
}

increase() {
    if [ "$1" != 'internal' ] && [ "$1" != 'external' ]; then
        _step="${1:-$WMRC_BACKLIGHT_STEP}"
        shift 1 2>/dev/null
    else
        _step="$WMRC_BACKLIGHT_STEP"
    fi
    if has_monitor internal && [ "$1" != 'external' ]; then
        _current="$(cat "$internal_file")"
        _max="$(cat "$internal_file_max")"
        _internal="$((_current+_step*_max/100))"
        _internal="$((_internal<_max?_internal:_max))"
        _internal="$((_internal>0?_internal:0))"
        echo "$_internal" | sudo tee "$internal_file" >/dev/null
        info 'Increase internal backlight' "$_internal"
    fi
    if has_monitor external && [ "$1" != 'internal' ]; then
        _current="$(cat "$external_file")"
        _current="$((_current+_step))"
        if ddcutil_write "$_current"; then
            info 'Increased external backlight' "$_current"
        else
            error 'Failed to increase external backlight' "$_current"
            ddcutil_read
        fi
    fi
}

decrease() {
    if [ "$1" != 'internal' ] && [ "$1" != 'external' ]; then
        _step="${1:-$WMRC_BACKLIGHT_STEP}"
        shift 1 2>/dev/null
    else
        _step="$WMRC_BACKLIGHT_STEP"
    fi
    if has_monitor internal && [ "$1" != 'external' ]; then
        _current="$(cat "$internal_file")"
        _max="$(cat "$internal_file_max")"
        _internal="$((_current-_step*_max/100))"
        _internal="$((_internal<_max?_internal:_max))"
        _internal="$((_internal>0?_internal:0))"
        echo "$_internal" | sudo tee "$internal_file" >/dev/null
        info 'Decrease internal backlight' "$_internal"
    fi
    if has_monitor external && [ "$1" != 'internal' ]; then
        _current="$(cat "$external_file")"
        _current="$((_current-_step))"
        if ddcutil_write "$_current"; then
            info 'Decreased external backlight' "$_current"
        else
            error 'Failed to decrease external backlight' "$_current"
            ddcutil_read
        fi
    fi
}

ddcutil_write() {
    if [ "$1" -gt 100 ] || [ "$1" -lt 0 ]; then
        warn 'External backlight value reached the limit'
        return 0
    fi
    if ! daemon_get_pid; then
        ddcutil setvcp 10 "$1" &
        _ddcutil_pid="$!"
        daemon_set_pid "$_ddcutil_pid"
        if wait "$_ddcutil_pid"; then
             echo "$1" > "$external_file"
        else
            return 1
        fi
    fi
}

ddcutil_read() {
    if ! daemon_get_pid; then
        daemon_set_pid "$$"
        ddcutil getvcp 10 | grep -Po 'current value *= *\K.*?(?=,)' > "$external_file"
    fi
}

off() {
    xset dpms force off
    info 'Monitors turned off'
}

on() {
    xset dpms force on
    info 'Monitors turned on'
}
