#!/bin/sh

export WMRC_DEPENDENCIES='xidlehook xset'

start() {
    if daemon_get_pid; then
        error "Screen guard daemon is already running!"
        return 1
    fi
    info "Starting screen guard daemon"
    blank_timeout="${1:-300}"
    lock_timeout="${2:-305}"
    call screen/lock generate_composite
    xset s off -dpms &
    xidlehook \
        --not-when-fullscreen \
        --not-when-audio \
        --timer "$blank_timeout" \
            "xset dpms force off" '' \
        --timer "$lock_timeout" \
            "wmrc start screen/lock detach" '' \
        > /dev/null &
    daemon_set_pid "$!"
}

