#!/bin/sh

export WMRC_DEPENDENCIES='feh'

start() {

  BCK_IMG="$HOME/Pictures/wallpaper.png"
  [ -f "$BCK_IMG" ] || \
    error "Wallpaper image '$BCK_IMG' is missing!" fatal 2

  DISPLAY=$DISPLAY feh --bg-fill "$BCK_IMG"

}
