#!/bin/sh

export WMRC_DEPENDENCIES='feh'

init() {
  info 'Set static wallpaper'
  BCK_IMG="$HOME/Pictures/wallpaper.png"
  if ! [ -f "$BCK_IMG" ]; then
    error "Wallpaper image '$BCK_IMG' is missing!"
    exit 2
  fi

  DISPLAY=$DISPLAY feh --bg-fill "$BCK_IMG"

}
