#!/bin/sh

export WMRC_DEPENDENCIES='feh convert jq curl bc printf xargs'

BCK_IMG="$HOME/Pictures/wallpaper-%s.png"
COMPOSITE="convert -colorspace Gray \( $BCK_IMG -evaluate multiply %.2f \) \( $BCK_IMG -evaluate multiply %.2f \) -compose plus -composite %s"
DELAY="$((150))"

LATLNG="$(echo "$WMRC_LOCATION" | sed 's|_|.|g; s|N|?lat=|; s|S|\&lng=|;')"

start() {
	if ! test -f "$(printf "$BCK_IMG" 'day')" || ! test -f "$(printf "$BCK_IMG" 'night')"; then
		error "Wallpaper images are missing!"
		return 1
	fi
	if daemon_get_pid; then
		error "Dynamic wallpaper daemon is already running!"
		return 1
	else
		daemon &
		daemon_set_pid "$!"
	fi
}

daemon() {
	while true; do
		api
		background
		sleep "$DELAY"
		debug "Next wallpaper" "$DELAY seconds"
	done
}

api() {
	api_new_date="$(date -u +%D)"
	if [ "$api_response" = '' ] || [ "$api_new_date" != "$api_date" ]; then
		api_date="$api_new_date"
		api_response="$(curl --silent "https://api.sunrise-sunset.org/json$LATLNG&formatted=0")"
		sunrise="$(echo "$api_response" | jq -r '.results.sunrise' | xargs date +%s -d)"
		sunset="$(echo "$api_response" | jq -r '.results.sunset' | xargs date +%s -d)"
	fi
	debug 'Sunrise' "$sunrise"
	debug 'Sunset' "$sunset"
}

background() {
	fade_period=3600
	now="$(date -u +%s)"
	prev_part="$part"
	part='night'
	if [ "$now" -gt $((sunset - fade_period / 2)) ]; then
		if [ "$now" -lt $((sunset + fade_period / 2)) ]; then
			part='sunset'
		fi
	elif [ "$now" -gt $((sunrise - fade_period / 2)) ]; then
		if [ "$now" -lt $((sunrise + fade_period / 2)) ]; then
			part='sunrise'
		else
			part='day'
		fi
	fi
	if [ "$part" = 'day' ] || [ "$part" = 'night' ]; then
		if [ "$part" = "$prev_part" ]; then
			debug "Skiping dynamic wallpaper update"
			return 0
		fi
	fi
	command=''
	case "$part" in
		'night'|'day')
			command="$(printf "DISPLAY=$DISPLAY feh --bg-fill $BCK_IMG\n" "$part")";
			;;
		'sunrise')
			day_mul="$(echo "scale=2;($now-($sunrise-$fade_period/2))/$fade_period" | bc)";
			night_mul="$(echo "scale=2;(1-$day_mul)" | bc)";
			debug "Day multiplier" "$day_mul"
			debug "Night multiplier" "$day_mul"
			command="$(
				printf "$COMPOSITE && DISPLAY=$DISPLAY feh --bg-fill %s" \
				'day' "$day_mul" 'night' "$night_mul" \
				"/tmp/dynamic_wallpaper.$USER.png" \
				"/tmp/dynamic_wallpaper.$USER.png"
			)";
			;;
		'sunset')
			night_mul="$(echo "scale=2;($now-($sunset-$fade_period/2))/$fade_period" | bc)";
			day_mul="$(echo "scale=2;(1-$night_mul)" | bc)";
			debug "Day multiplier" "$day_mul"
			debug "Night multiplier" "$day_mul"
			command="$(
				printf "$COMPOSITE && DISPLAY=$DISPLAY feh --bg-fill %s" \
				'day' "$day_mul" 'night' "$night_mul" \
				"/tmp/dynamic_wallpaper.$USER.png" \
				"/tmp/dynamic_wallpaper.$USER.png"
			)";
			;;
	esac
	info "Updating dynamic wallpaper" "$part"
	eval "$command"
}
