#!/bin/sh

export WMRC_DEPENDENCIES='feh'

WMRC_WALLPAPER="${WMRC_WALLPAPER:-$HOME/Pictures/wallpaper.png}"
WMRC_WALLAPER_FIT="${WMRC_WALLAPER_FIT:-fill}"

init() {
  image="$WMRC_WALLPAPER"
  info 'Set static wallpaper' "$image"
  if ! test -f "$image" ; then
    error 'Wallpaper image not found' "$image"
    return 1
  fi
  DISPLAY=$DISPLAY feh "--bg-$WMRC_WALLAPER_FIT" "$image"
}
