#! /usr/bin/env dash
# WMRC_DEPS: polybar, pgrep, xrandr
# WMRC_FLAGS:

start() {

  [ -z "$(pgrep -u "$(whoami)" polybar)" ] || \
    error "Polybar is already running!" fatal 2

  local WLP
  local ENP
  local MNT
  local MONITORS
  local M_PRIMARY
  local M_ALL
  local M

  WLP="$(ip -o link show | awk -F': ' '{print $2}' | grep wlp)"
	ENP="$(ip -o link show | awk -F': ' '{print $2}' | grep enp)"
	MNT="$(lsblk | awk '/\//{printf "mount-"NR-2" = "$7"\n"}')"

  M_PRIMARY="$(xrandr --query | grep " primary" | cut -d" " -f1)"
  M_ALL="$(xrandr --query | grep " connected" | cut -d" " -f1)"

  case "$2" in
    primary)
      MONITORS="$M_PRIMARY";;
    ""|all)
      MONITORS="$M_ALL";;
    *)
      for M in $(echo "$@" | cut -d' ' -f2- | sed "s/ /\n/g"); do
        echo "$M_ALL" | grep -q "^$M$" && \
          MONITORS="$MONITORS $M" || \
          error "Monitor '$M' is not connected!"
      done;;
  esac

  for M in $MONITORS; do

    WIDTH="$(xrandr --listmonitors | perl -nle "/$M (\d+)/ && print \$1")"
    HEIGHT="$(xrandr --listmonitors | perl -nle "/$M \d+\/\d+x(\d+)/ && print \$1")"

    if [ "$M" = "$M_PRIMARY" ]; then
      [ "$WIDTH" -ge 1920 ] && \
        MOD_L="bspwm window" || MOD_L="bspwm"
      MOD_C=""
      MOD_R="battery wireless wired cpu memory fan temperature filesystem pulseaudio keyboard date"
      NOTIF="right"
    else
      MOD_L="bspwm"
      MOD_C="deadbeef"
      MOD_R="updates monitor host date"
      NOTIF="none"
    fi

    MONITOR="$M" WLP="$WLP" ENP="$ENP" MNT="$MNT" ML="$MOD_L" MC="$MOD_C" MR="$MOD_R" NOTIF="$NOTIF" polybar --reload "main" &

  done

}

stop() {

  [ -z "$(pgrep -u "$(whoami)" polybar)" ] && \
    error "Polybar is not running!" fatal 3

  killall -u "$(whoami)" -9 polybar > /dev/null

}

. "$MODULES/init"