#! /bin/sh

MODULES=$(realpath "$(dirname $0)/../")

if [ -e /tmp/$USER.bspwm_hardened ]; then

	LOCK_CMD="$MODULES/screen/physlock"

	pactl set-sink-mute 0 1

	for MONITOR in $(bspc query -M); do
    	bspc desktop -f 0 -m $MONITOR
	done

else

	LOCK_CMD="$MODULES/screen/i3lock"

fi

if [ -z $DISPLAY ]; then
	if [ -e "/tmp/x11_$USER" ]; then
	    export DISPLAY=$(cat "/tmp/x11_$USER")
	else
		$MODULES/interface/notify error "Error occured while locking the screen! \$DISPLAY is not set."	
	fi
    
fi

"$MODULES/screen/backlight" = 100

LANG=$(xkb-switch -p)
CAPS=$(xset -q | grep -Pzo "Caps Lock: +(on|off)" | sed "s/^.*: *//")

xkb-switch -s us
if [ "$CAPS" == "on" ]; then
	xdotool key Caps_Lock
fi

if [ "$1" == "systemd" ]; then

	$LOCK_CMD

else

	sleep 0.2
	xset dpms force off

	WAIT=$("$LOCK_CMD" -n)

	xkb-switch -s "$LANG"
	if [ "$CAPS" == "on" ]; then
		xdotool key Caps_Lock
	fi

fi