#! /usr/bin/env dash

wid=$1
class=$2
instance=$3
consequences=$4

case "$class" in
	firefox|firefoxdeveloperedition)
		# Picture in picture
		xprop -id "$wid" 'WM_NAME' | grep -q 'Picture-in-Picture' && {
			rec="$(
				xwininfo -id "$wid" | awk '
					/Absolute upper-left X:/ {x=int($NF)};
					/Absolute upper-left Y:/ {y=int($NF)};
					/Width:/ {w=int($NF)};
					/Height:/ {h=int($NF)};
					END {
						ow = w;
						oh = h;
						if (w > 640) {
							ar = w / h;
							w = 640;
							h = w / ar;
						}
						if (h > 320) {
							ar = w / h;
							h = 320;
							w = h * ar;
						}
						printf("rectangle=%ix%i+%i+%i",w*3/4,h*3/4,x+ow-w*3/4-20,y+oh-h*3/4-45)
					};'
			)"
			echo "state=floating sticky=on $rec"
		}
		;;
	Sxiv|feh)
		echo "state=pseudo_tiled"
		;;
	Peek)
		echo "state=floating"
		echo "rectangle=640x480+363+144"
		;;
	Dino|dino|Signal|Wire)
		echo "desktop=3"
		;;
	freezer|audiotube|Supersonic)
		echo "desktop=5"
		;;
	thunderbird)
		echo "desktop=0"
		;;
esac
