#!/bin/sh

export WMRC_DEPENDENCIES='screen/lock hardware/power hardware/thinkpad sudo xset'

WMRC_AUTO_SUSPEND_DELAY="${WMRC_AUTO_SUSPEND_DELAY:-60}"

monitor_inactive() {
	if xset q | grep -q 'Monitor is Off'; then
		return 0
	fi
	if [ -e '/proc/acpi/button/lid/LID/state' ]; then
		grep -q 'closed' /proc/acpi/button/lid/LID/state
	else
		return 1
	fi
}

lockscreen_active() {
	WMRC_LOG_LEVEL=none call screen/lock daemon_get_pid
}

probe_loop() {
	info 'Started auto suspend watchdog'
	call hardware/thinkpad get_attention
	while true; do
		sleep "$WMRC_AUTO_SUSPEND_DELAY"
		debug 'Checking conditions for auto suspend'
		if lockscreen_active; then
			info 'Lockscreen inactivity, suspending system'
		elif monitor_inactive; then
			info 'Monitor lid closed, suspending system'
		else
			info 'Interaction detected'
			break
		fi
		call hardware/power suspend
	done
	info 'Stopping daemon'
	call hardware/thinkpad turn_off_leds
	exit
}

start() {
	if daemon_get_pid; then
		error 'Auto suspend watchdog is already running!'
		return 1
	fi
	probe_loop &
	daemon_set_pid "$!"
}

stop() {
	call hardware/thinkpad turn_off_leds
	if daemon_get_pid; then
        info 'Stopped auto suspend watchdog'
		daemon_kill
	fi
}
