#!/bin/sh

export WMRC_DEPENDENCIES='sudo xset'

WMRC_AUTO_SUSPEND_DELAY="${WMRC_AUTO_SUSPEND_DELAY:-20}"

monitor_inactive() {
	if xset q | grep -q 'Monitor is Off'; then
		return 0
	fi
	if [ -e '/proc/acpi/button/lid/LID/state' ]; then
		grep -q 'closed' /proc/acpi/button/lid/LID/state
	else
		return 1
	fi
}

start() {
	if daemon_get_pid; then
		error 'Auto suspend watchdog is already running!'
		return 1
	fi
	daemon_set_pid "$$"
	info 'Started auto suspend watchdog'
	while true; do
        call hardware/thinkpad get_attention
		sleep "$WMRC_AUTO_SUSPEND_DELAY"
		debug 'Checking conditions for auto suspend'
		if monitor_inactive || wmrc status screen/lock 2>&1 | grep -q 'Process id'; then
			info 'Screen inactivity, suspending system'
			wmrc unit suspend
		fi
	done
	stop
}

stop() {
	call hardware/thinkpad turn_off_leds
	if daemon_get_pid; then
        info 'Stopped auto suspend watchdog'
		daemon_kill
	fi
}
