#!/bin/sh

export WMRC_DEPENDENCIES='sudo'

WMRC_TRACKPOINT_SENSITIVITY_X230="${WMRC_TRACKPOINT_SENSITIVITY_X230:-220}"
WMRC_TRACKPOINT_SENSITIVITY_X13="${WMRC_TRACKPOINT_SENSITIVITY_X13:-30}"

detect_model() {
	if [ -n "$thinkpad_model" ]; then
		return 0
	fi
	if grep -q "ThinkPad" "/sys/devices/virtual/dmi/id/product_family"; then
		thinkpad_model="$(cut -d' ' -f2 /sys/devices/virtual/dmi/id/product_family)"
		if [ -z "$thinkpad_model" ]; then
			warn "Device is not a ThinkPad"
			return 1
		fi
		debug "Detected model" "ThinkPad $thinkpad_model"
		return 0
	else
		warn "Device is not a ThinkPad"
		return 1
	fi
}

configure_trackpoint() {
	if ! detect_model; then
		return 1
	fi
	file_sensitivity="$(find /sys/devices/platform/i8042/ -name 'sensitivity')"
	file_select="$(find /sys/devices/platform/i8042/ -name 'press_to_select')"
	info 'Set TrackPoint sensitivity'
	for file in $file_sensitivity; do
		debug 'Set sensitivity' "$file"
		eval "echo \$WMRC_TRACKPOINT_SENSITIVITY_$thinkpad_model" | sudo tee "$file" >/dev/null
	done
	info 'Turn off TrackPoint tap select'
	for file in $file_select; do
		debug 'Turn off tap select' "$file"
		printf '0' | sudo tee "$file" >/dev/null
	done
}

turn_off_leds() {
	info 'Turn off LEDs'
	# Legacy
	if [ -e '/proc/acpi/ibm/led' ]; then
		debug 'Turn off power LED'
		echo '0 off' | sudo tee /proc/acpi/ibm/led >/dev/null
	fi
	# Modern
	for led in 'power' 'lid_logo_dot'; do
		file="/sys/devices/platform/thinkpad_acpi/leds/tpacpi::$led/brightness"
		debug "Turn off '$led' LED" "$file"
		if [ -e "$file" ]; then
			echo '0' | sudo tee "$file" >/dev/null
		fi
	done
}

keyboard_backlight() {
	info 'Turn off keyboard backlight'
	file='/sys/devices/platform/thinkpad_acpi/leds/tpacpi::kbd_backlight/brightness'
	if [ -e "$file" ]; then
		echo "${1:-2}" | sudo tee "$file" >/dev/null
	fi
}

get_attention() {
	info 'Get user attention'
	if [ -e '/proc/acpi/ibm/led' ]; then
		echo '0 blink' | sudo tee /proc/acpi/ibm/led >/dev/null
	fi
}

init() {
	configure_trackpoint
	turn_off_leds
}
