#! /bin/sh

MODULES=$(realpath "$(dirname $0)/../")

APPS=(
	"unclutter -idle 1"
	"redshift-qt"
	"dunst"
	"flameshot"
	"keepassxc"
	"synergy"
	"signal-desktop --start-in-tray"
	"gajim"
	"wire-desktop --startup"
)

function start() {
	for APP in "${APPS[@]}"; do
		nohup $APP&>/dev/null&
	done
}

function stop() {
	USER=$(whoami)
	for APP in "${APPS[@]}"; do
		WAIT=$(killall -u "$USER" -9 "${APP%% *}")
	done
}

function restart() {
	stop
	start
}

if [ -z "$1" ]; then

	start

else

	if ! [ -z "$2" ]; then
		
		APPS_ARG="${@:2}"
		APPS_TARGET=()
		
		for A in "${APPS_ARG[@]}"; do
			for APP in "${APPS[@]}"; do
				if [[ "${APP%% *}" == "$A" ]]; then
					APPS_TARGET+=("$APP")
				fi
			done
		done

		APPS=("${APPS_TARGET[@]}")

	fi
	
	$1
	
fi