#! /bin/sh

MODULES=$(realpath "$(dirname $0)/../")

PATHS=(
	"/home/filiparag/Downloads/Remote"
	"/home/filiparag/Public"
)

function start() {
	for P in "${PATHS[@]}"; do
		nohup sudo mount "$P"&>/dev/null&
	done
}

function stop() {
	for P in "${PATHS[@]}"; do
		WAIT=$(sudo umount "$P")
	done
}

function restart() {
	stop
	start
}

if [ -z "$1" ]; then

	start

else

	if ! [ -z "$2" ]; then
		
		PATHS_ARG="${@:2}"
		PATHS_TARGET=()
		
		for P in "${PATHS_ARG[@]}"; do
			for PT in "${PATHS[@]}"; do
				if [[ "${PT%% *}" == "$P" ]]; then
					PATHS_TARGET+=("$P")
				fi
			done
		done

		PATHS=("${PATHS_TARGET[@]}")

	fi
	
	$1
	
fi