#! /bin/sh

function start() {
	x0vncserver -SecurityTypes=TLSVnc \
		--PasswordFile=$HOME/.vnc/passwd &>/dev/null&
	echo a
}

function stop() {
	killall -9 x0vncserver &> /dev/null
}

function restart() {
	if ! [ -z "$(pgrep -u $USER x0vncserver)" ]; then
		stop
		start
	fi
}

if [ -z "$1" ]; then
	start
else
	$1
fi