#! /bin/bash

export WM="bspwm"

MODULES="$(dirname "$0")/modules"

MODE="start"
RC_CONF="$MODULES/rc.conf"

if [ "$1" == "--dry-run" ]; then
	if [ -n "$2" ]; then
		MODE="$2"
	fi
elif [ -n "$1" ]; then
	MODE="$1"
fi

# Remove comments and empty lines
RC_LIST="$(cat "$RC_CONF" | sed '/^#/d; /^$/d; s:#.*$::g')"

# Find target section
RC_SECTION="$(printf "$RC_LIST" | grep -Pzo "\["$MODE"\]\n?([^\[]+\n?)*" | tr '\0' '\n')"
if [ -z "$RC_SECTION" ]; then
	$MODULES/interface/notify error "Unable to execute bspwm section <i>'$MODE'</i>! Section not found."
	exit 1
fi

ENTRYLIST=""
for ENTRY in $(printf "$RC_SECTION" | sed '1d'); do

	# Verify entry format
	VERIFY_ENTRY="$(printf "$ENTRY" | grep -Pzo "([^\[]+\n?)*" | tr '\0' '\n')"
	printf "$VERIFY_ENTRY"
	exit
	if [ -z "$RC_SECTION" ]; then
		$MODULES/interface/notify error "Unable to execute bspwm section <i>'$MODE'</i>! Section not found."
		exit 1
	fi

	# Separate section and modules
	ENTRY_SEC="$(printf "$ENTRY" | sed 's:/.*$::')"
	ENTRY_CMDS="$(printf "$ENTRY" | sed 's:^.*/::')"

	# Replace asterisk with all modules in directory
	if [[ "$ENTRY_CMDS" =~ "*" ]]; then
		SEC_ALL_ENTRIES="$(find "$MODULES/$ENTRY_SEC" -type f -printf '%P,' | sed 's/,$//')"
		ENTRY_CMDS=$(printf "$ENTRY_CMDS" | awk "{gsub(\"*\",\"$SEC_ALL_ENTRIES\"); print}")
	fi

	ENTRY_CMDS="$(printf "$ENTRY_CMDS" | sed 's/,/\n/g')"

	for ENTRY_CMD in $ENTRY_CMDS; do
		ENTRYLIST="$ENTRYLIST$ENTRY_SEC/$ENTRY_CMD\n"
	done

done

RUNLIST=$(printf "$ENTRYLIST" | awk '!a[$0]++' | awk 'NF')

printf "$RUNLIST\n"

################################################################################
exit

if [ -z $(grep "\[$MODE\]" "$MODULES/rc.conf") ]; then

	$MODULES/interface/notify error "Unable to execute bspwm section <i>'$MODE'</i>! Section not found."
	exit 1

fi

RUNCFG=$(cat "$MODULES/rc.conf" | \
		 sed '/^#/d; /^$/d; 0,/^\['"$MODE"'\]/d; /\[.*/,$d')

RUNLIST=""

for ENTRY in $(printf "$RUNCFG"); do

	MDIR=$(echo $ENTRY | sed "s:\/.*::")
	MLIST=$(echo $ENTRY | sed "s:.*\/::; s:,:\n:g")

	ENTRYLIST="$(printf "$MLIST\n" | sed '/*/d')"
	ENTRYLIST=$(printf "$ENTRYLIST" | sed "s:^:$MDIR/:;")

	if [[ "$MLIST" =~ "*" ]]; then
		ENTRYLIST="$ENTRYLIST\n$(find "$MODULES/$MDIR" -type f -printf "$MDIR/%P\n")"
	fi

	RUNLIST="$RUNLIST$ENTRYLIST\n"

done

RUNLIST=$(printf "$RUNLIST" | awk '!a[$0]++' | awk 'NF')

if [ "$1" == "--dry-run" ]; then

	printf "[$MODE]\n$RUNLIST\n"
	exit

fi

for MOD in $(printf "$RUNLIST"); do

	MOD_CMD="$MOD"
	MOD_ARGS=""
	if [[ "$MOD" =~ "(" ]]; then
		MOD_CMD="$(printf "$MOD" | sed "s/(.*//")"
		MOD_ARGS="$(printf "$MOD" | sed 's/.*(//; s/)$//; s/\;/ /g')"
	fi

	MPATH="$MODULES/$MOD_CMD"

	if [ -f "$MPATH" ]; then

		if [ ! -x "$MPATH" ]; then		
			chmod +x "$MPATH"
		fi

		if grep -q "# RC_ASYNC_LOCK" "$MPATH"; then

			WAIT=$("$MPATH" $MOD_ARGS &> /dev/null&)

		else
		
			nohup "$MPATH" $MOD_ARGS &> /dev/null&
		
		fi

	else

		$MODULES/interface/notify error "Unable to execute bspwm module <i>'$MOD'</i>! File is missing."

	fi

done
