#! /bin/bash

export WM="bspwm"

MODULES="$(dirname "$0")/modules"

MODE="start"

if [ "$1" == "--dry-run" ]; then
	if [ -n "$2" ]; then
		MODE="$2"
	fi
elif [ -n "$1" ]; then
	MODE="$1"
fi

if [ -z $(grep "\[$MODE\]" "$MODULES/rc.conf") ]; then

	$MODULES/interface/notify error "Unable to execute bspwm section <i>'$MODE'</i>! Section not found."
	exit 1

fi

RUNCFG=$(cat "$MODULES/rc.conf" | \
		 sed '/^#/d; /^$/d; 0,/^\['"$MODE"'\]/d; /\[.*/,$d')

RUNLIST=""

for ENTRY in $(printf "$RUNCFG"); do

	MDIR=$(echo $ENTRY | sed "s:\/.*::")
	MLIST=$(echo $ENTRY | sed "s:.*\/::; s:,:\n:g")

	ENTRYLIST="$(printf "$MLIST\n" | sed '/*/d')"
	ENTRYLIST=$(printf "$ENTRYLIST" | sed "s:^:$MDIR/:;")

	if [[ "$MLIST" =~ "*" ]]; then
		ENTRYLIST="$ENTRYLIST\n$(find "$MODULES/$MDIR" -type f -printf "$MDIR/%P\n")"
	fi

	RUNLIST="$RUNLIST$ENTRYLIST\n"

done

RUNLIST=$(printf "$RUNLIST" | awk '!a[$0]++' | awk 'NF')

if [ "$1" == "--dry-run" ]; then

	printf "[$MODE]\n$RUNLIST\n"
	exit

fi

for MOD in $(printf "$RUNLIST"); do

	MOD_CMD="$MOD"
	MOD_ARGS=""
	if [[ "$MOD" =~ "(" ]]; then
		MOD_CMD="$(printf "$MOD" | sed "s/(.*//")"
		MOD_ARGS="$(printf "$MOD" | sed 's/.*(//; s/)$//; s/\;/ /g')"
	fi

	MPATH="$MODULES/$MOD_CMD"

	if [ -f "$MPATH" ]; then

		if [ ! -x "$MPATH" ]; then		
			chmod +x "$MPATH"
		fi

		if grep -q "# RC_ASYNC_LOCK" "$MPATH"; then

			WAIT=$("$MPATH" $MOD_ARGS &> /dev/null&)

		else
		
			nohup "$MPATH" $MOD_ARGS &> /dev/null&
		
		fi

	else

		$MODULES/interface/notify error "Unable to execute bspwm module <i>'$MOD'</i>! File is missing."

	fi

done
