#!/bin/sh

export WMRC_DEPENDENCIES='setxkbmap numlockx xmodmap'

WMRC_KEYBOARD_LANGUAGES="${WMRC_KEYBOARD_LANGUAGES:-us,rs,rs}"
WMRC_KEYBOARD_VARIANTS="${WMRC_KEYBOARD_VARIANTS:-,latin,}"

layout() {
  info "Set keyboard layout" "$WMRC_KEYBOARD_LANGUAGES"
  setxkbmap \
    -layout "$WMRC_KEYBOARD_LANGUAGES" \
    -variant "$WMRC_KEYBOARD_VARIANTS" \
    -option grp:alt_shift_toggle
  info "Turn on Num Lock"
  numlockx on
}

keybinds() {
  if WMRC_LOG_LEVEL=none call hardware/thinkpad detect_model; then
    info "Change key bindings for ThinkPad"
    xmodmap -e "keycode 112 = Home"
    xmodmap -e "keycode 117 = End"
    xmodmap -e "keycode 107 = Menu"
    xmodmap -e "keycode 110 = Prior"
    xmodmap -e "keycode 115 = Next"
  else
    info "No keybidings changed"
  fi
}

init() {
  layout
  keybinds
}
