#!/bin/sh

export WMRC_DEPENDENCIES='pgrep sxhkd'

reload() {
  if ! daemon_get_pid; then
		error "Sxhkd is not running!"
		return 1
	fi
  info "Reloading sxhkd configuration"
  pkill -USR1 -x sxhkd
}

start() {
  if daemon_get_pid; then
		error "Sxhkd is already running!"
		return 1
	fi
  sxhkd &
  daemon_set_pid "$!"
}
