#!/bin/sh

export WMRC_DEPENDENCIES='pgrep sxhkd'

reload() {

  [ -z "$(pgrep -u "$(whoami)" sxhkd)" ] && \
    {
      error "Sxhkd is not running!"
      exit 2
    }

  pkill -USR1 -x sxhkd

}

start() {

  [ -z "$(pgrep -u "$(whoami)" sxhkd)" ] || \
    {
      error "Sxhkd is already running!"
      exit 2
    }

  sxhkd &

}

stop() {

  [ -z "$(pgrep -u "$(whoami)" sxhkd)" ] && \
    {
      error "Sxhkd is not running!"
      exit 3
    }

  killall -u "$(whoami)" -9 sxhkd > /dev/null

}
