#! /bin/sh

# Visual options
bspc config top_padding 				0
bspc config border_width 				1
bspc config window_gap          		0
bspc config split_ratio         		0.5
bspc config borderless_monocle  		true
bspc config single_monocle 				true
bspc config gapless_monocle     		true
bspc config auto_alternate 				true
bspc config auto_cancel 				true
bspc config normal_border_color 		"#040404"
bspc config active_border_color 		"#454545"
bspc config focused_border_color 		"#606060"
bspc config urgent_border_color 		"#fdd835"
bspc config ignore_ewmh_fullscreen      none
bspc config pointer_follows_monitor		true
bspc config pointer_follows_focus		false

# Multihead behavior
bspc config remove_disabled_monitors 	true
bspc config remove_unplugged_monitors 	true

# Focusing behavior
bspc config focus_follows_pointer 		false
bspc config history_aware_focus 		true

# Rules
bspc rule -a File-roller 				pseudo_tiled=on
bspc rule -a feh 						pseudo_tiled=on

# Default cursor
xsetroot -cursor_name 					left_ptr