#! /bin/sh

MODULES=$(realpath "$(dirname $0)/../")

if [ ! -e /tmp/$USER.bspwm_hardened ]; then

	if [ "$1" == "restart" ]; then

		WAIT=$(killall -q polybar)
		while pgrep -u $UID -x polybar >/dev/null; do sleep 1; done

	fi


	WLP=$(ip -o link show | awk -F': ' '{print $2}' | grep wlp)
	ENP=$(ip -o link show | awk -F': ' '{print $2}' | grep enp)
	MNT=$(lsblk | awk '/\//{printf "mount-"NR-2" = "$7"\n"}')

	if type "xrandr"; then
		for m in $(xrandr --query | grep " connected" | cut -d" " -f1); do
			MONITOR=$m WLP=$WLP ENP=$ENP MNT=$MNT polybar --reload main &
		done
	else
		polybar --reload main &
	fi

fi
