#!/bin/sh

export WMRC_DEPENDENCIES=''
export WMRC_LIBRARIES='notify'

WMRC_MAIN_BATTERY="${WMRC_MAIN_BATTERY:-BAT0}"

daemon() {
  info "Started low battery daemon"
  WARN_LEVEL=20
  CHECK_FREQ=30
  NOTIFY_DELAY=55
  NOTIFY_TIME=5
  NOTIFY_TPREV=0

  while true; do

    CURR_LEVEL=$(cat "/sys/class/power_supply/$WMRC_MAIN_BATTERY/capacity")
    CURR_STATUS=$(cat "/sys/class/power_supply/$WMRC_MAIN_BATTERY/status")
    CURR_TIMEST=$(date +%s)

    debug "Check battery level"

    if [ "$CURR_LEVEL" -le "$WARN_LEVEL" ] && \
       [ "$CURR_TIMEST" -ge "$(( NOTIFY_TPREV + NOTIFY_DELAY ))" ] && \
       [ "$CURR_STATUS" = "Discharging" ]; then

      NOTIFY_TPREV="$CURR_TIMEST"

      notify -u low -t $(( NOTIFY_TIME * 1000 )) \
        -i battery-empty-charging "Low battery" "Only $CURR_LEVEL% charge remaining!"

      warn "Low battery level" "$CURR_LEVEL%"

      sleep "$NOTIFY_DELAY"

    else

      sleep "$CHECK_FREQ"

    fi

  done

}

start() {
  if ! test -d "/sys/class/power_supply/$WMRC_MAIN_BATTERY"; then
    warn "System has no battery!" "$WMRC_MAIN_BATTERY"
    return
  fi
  if daemon_get_pid; then
		error "Low battery daemon is already running!"
		return 1
	else
		daemon &
		daemon_set_pid "$!"
	fi
}

