#!/bin/sh

export WMRC_DEPENDENCIES='dunstify'

NO_TITLE="Notification has no title provided!"

ask() {

  [ -z "$2" ] && \
    {
      error "$NO_TITLE"
      exit 2
    }
  echo "[Prompt] $2: $3" | sed 's:<i>::g; s:</i>::g' >&1

  INDEX=1
  CHOICES=""
  for P in "$@"; do
    [ $INDEX -gt 3 ] && \
      CHOICES="$CHOICES -A $INDEX,$(echo "$P" | sed "s/ /_/g")"
    INDEX=$((INDEX + 1))
  done

  [ -z "$CHOICES" ] && \
    {
      error "Prompt '$1' has no answer options provided!"
      exit 3
    }

  ANS="$(dunstify -u low -i "dialog-question" "$1" "$2" -a ask $CHOICES)"

  [ "$ANS" -lt 4 ] && \
    {
      error "Prompt '$1' not answered!"
      exit 4
    }

  INDEX=1
  for P in "$@"; do
    [ "$INDEX" = "$ANS" ] && echo "$P" && exit
    INDEX=$((INDEX + 1))
  done

}

info() {

  [ -z "$1" ] && \
    {
      error "$NO_TITLE"
      exit 2
    }
  echo "[Info] $1: $2" | sed 's:<i>::g; s:</i>::g' >&1
  dunstify -u low -i "dialog-info" "$1" "$2"

}

warn() {

  [ -z "$1" ] && \
    {
      error "$NO_TITLE"
      exit 2
    }
  echo "[Warning] $1: $2" | sed 's:<i>::g; s:</i>::g' >&1
  dunstify -u low -i "dialog-warning" "$1" "$2"

}

err() {

  [ -z "$1" ] && \
    {
      error "$NO_TITLE"
      exit 2
    }
  echo "[Error] $1: $2" | sed 's:<i>::g; s:</i>::g' >&2
  dunstify -u low -i "dialog-error" "$1" "$2"

}

pause() {

  pkill -u $USER -USR1 dunst

}

resume() {

  pkill -u $USER -USR2 dunst

}
