#!/bin/sh

export WMRC_DEPENDENCIES='picom'

start() {

  [ -z "$(pgrep -u "$(whoami)" picom)" ] || \
    {
      error "Picom is already running!"
      exit 2
    }

  picom &

}

stop() {

  [ -z "$(pgrep -u "$(whoami)" picom)" ] && \
    {
      error "Picom is not running!"
      exit 3
    }

  killall -u "$(whoami)" -9 picom > /dev/null

}
