#!/bin/sh

export WMRC_DEPENDENCIES='polybar pgrep xrandr'

export DAEMON_PID
export _pid_file

start() {

  if daemon_get_pid; then
		error "Polybar is already running!"
		return 1
	fi

  info "Starting polybar"

  WLP="$(ip -o link show | awk -F': ' '{print $2}' | grep -E '^(wlp|wlan)' | head -n 1)"
	ENP="$(ip -o link show | awk -F': ' '{print $2}' | grep -E '^(enp|end|eth)' | head -n 1)"
	MNT="$(lsblk | awk '/\//{printf "mount-"NR-2" = "$7"\n"}')"

  info 'Wireless network' "${WLP:-not detected}"
  info 'Wired network' "${ENP:-not detected}"

  M_PRIMARY="$(xrandr --query | grep " primary" | cut -d" " -f1)"
  M_ALL="$(xrandr --query | grep " connected" | cut -d" " -f1)"

  info 'Primary monitor' "${M_PRIMARY:-not configured}"
  info 'All monitors' "${M_ALL:-not detected}"

  case "$2" in
    primary)
      MONITORS="$M_PRIMARY";;
    ""|all)
      MONITORS="$M_ALL";;
    *)
      for M in $(echo "$@" | cut -d' ' -f2- | sed "s/ /\n/g"); do
        if echo "$M_ALL" | grep -q "^$M$"; then
          MONITORS="$MONITORS $M" || \
          warn "Monitor '$M' is not connected!"
        fi
      done;;
  esac

  for M in $MONITORS; do

    WIDTH="$(xrandr --listmonitors | perl -nle "/$M (\d+)/ && print \$1")"
    HEIGHT="$(xrandr --listmonitors | perl -nle "/$M \d+\/\d+x(\d+)/ && print \$1")"

    if [ "$M" = "$M_PRIMARY" ]; then
      if [ "$WIDTH" -ge 3440 ]; then
        BAR_TYPE='wide'
        MOD_L="bspwm window"
        MOD_C="playerctl"
        MOD_R="battery wireless wired cpu memory fan temperature filesystem pulseaudio keyboard date"
      elif [ "$WIDTH" -ge 1920 ]; then
        BAR_TYPE='medium'
        MOD_L="bspwm window"
        MOD_C=""
        MOD_R="battery wireless wired cpu memory fan temperature filesystem pulseaudio keyboard date"
      else
        BAR_TYPE='narrow'
        MOD_L="bspwm"
        MOD_C=""
        MOD_R="battery wireless wired cpu memory fan temperature pulseaudio keyboard date"
      fi
      [ "$WIDTH" -ge 1920 ] && \
      NOTIF="right"
    else
      MOD_L="bspwm"
      MOD_C="playerctl"
      MOD_R="updates pulseaudio host date"
      NOTIF="none"
    fi

    export WLP
    export ENP
    export MNT
    export WIDTH
    export HEIGHT
    export MONITOR="$M"
    export ML="$MOD_L"
    export MC="$MOD_C"
    export MR="$MOD_R"
    export NOTIF="$NOTIF"

    LOG_FILE="$(echo "$_pid_file" | sed "s/\.pid$/::$M.log/")"

    if [ "$M" = "$M_PRIMARY" ]; then
      info "Adding $BAR_TYPE bar to primary monitor" "$M"
    else
      info "Adding $BAR_TYPE bar to auxiliary monitor" "$M"
    fi

    debug 'Modules left' "$MOD_L"
    debug 'Modules middle' "$MOD_C"
    debug 'Modules right' "$MOD_R"
    debug 'Notification position' "$NOTIF"

    polybar --reload "main" 1>"$LOG_FILE" 2>"$LOG_FILE" &

    daemon_set_pid "$!"

  done

}

stop() {

  [ -z "$(pgrep -u "$(whoami)" polybar)" ] && \
    error "Polybar is not running!"

  info "Stopping polybar"
  daemon_kill
  killall -u "$(whoami)" -9 polybar 2> /dev/null
  if test -f "$DAEMON_PID"; then
    xargs kill -9 < "$DAEMON_PID"
    rm -f "$DAEMON_PID"
  fi

}
