#!/bin/sh

export WMRC_DEPENDENCIES='awk rofi xdotool xclip perl xdg-open'

get_dpi() {
  dpi="$(awk '$1=="Xft.dpi:"{print $2}' "$HOME/.Xresources")"
}

start() {
  info "Show rofi menu"
  get_dpi
  rofi -no-lazy-grab \
    -dpi "$dpi" \
    -modi drun,run,window,ssh,combi \
    -combi-modi drun,window,run,ssh \
    -columns 2 \
    -show combi \
    -show-icons true \
    -terminal "$TERMINAL"
}

calc() {
  info "Show rofi calculator"
  get_dpi
  rofi -no-lazy-grab \
      -dpi "$dpi" \
      -modi calc \
      -show calc
}

files() {

  info "Show rofi file browser"
  CURRENT="$HOME"
  get_dpi

  while [ -n "$CURRENT" ]; do

    LL="$(find "$CURRENT" -maxdepth 1 \
        -not -path "$CURRENT" \
        -not -name '.*' \
        -printf '%P\n' | \
        sort)"
    [ "$CURRENT" != "/" ] && LL=".\n..\n$LL"

    CUR="$CURRENT"
    [ "$(echo "$CUR" | wc -m)" -gt 32 ] && \
      CUR="$(echo "$CUR" | awk -F/ '{for (i=1;i<NF;i++) \
          $i=substr($i,1,1+($i~/^[.]/))} 1' OFS=/)"

    SEL="$(echo "$LL" |
      rofi -dpi "$dpi" -dmenu -p "$CUR" -i \
      -columns 1)"

    [ -z "$SEL" ] && return

    CURRENT="$(realpath "$CURRENT/$SEL")"

    if [ "$SEL" = "." ]; then
      "$FILEMGR" "$CURRENT" &
      return
    elif [ "$SEL" != ".." ] && ! [ -d "$CURRENT" ]; then
      xdg-open "$CURRENT" &
      return
    fi

  done

}

character() {

  info "Show rofi character picker"
  get_dpi

  # Unicode Emoji generation script:
  # curl https://unicode.org/Public/emoji/15.0/emoji-test.txt | \
  #   awk '
  #     /^# group/ {
  #       g=tolower($3);
  #     }
  #     /^# subgroup/ {
  #       sg=tolower($3);
  #     }
  #     /; fully-qualified/ {
  #       gsub(/^.*fully-qualified\s+#\s+/,"",$0);
  #       $2="";
  #       emote=$1;
  #       $1="";
  #       gsub(/(^\s*)|:|,|\./,"",$0);
  #       gsub(/\s+/,"-",$0);
  #       print emote "\t" g "/" sg "/" tolower($0);
  #     }'

  CHARACTER_FILE="$HOME/.cache/characters.txt"

  [ -f "$CHARACTER_FILE" ] || \
    {
      error "Character list file '$CHARACTER_FILE' is missing!"
      exit 2
    }

  SEL="$(
    rofi -dpi "$dpi" -dmenu -p 'character' -i \
    -columns 3 \
		-icon-theme -font "Twitter Color Emoji 11" < "$CHARACTER_FILE"
  )"

  if [ -n "$SEL" ]; then

    CHAR="$(echo "$SEL" | cut -f1)"

    printf '%s' "$CHAR" | xdotool type "$CHAR"
    printf '%s' "$CHAR" | xclip -selection clipboard

  fi

}
