#! /usr/bin/env dash
# WMRC_DEPS: rofi, xdotool, xclip, perl, xdg-open
# WMRC_FLAGS:

start() {

  rofi -no-lazy-grab -modi drun,run,window,ssh,combi \
    -combi-modi drun,window,run,ssh \
    -columns 2 \
    -show combi \
    -show-icons true \
    -terminal "$TERMINAL"

}

calc() {

  rofi -no-lazy-grab -modi calc -show calc

}

movewindow() {
  
 bspc query -N -n .leaf | xargs -I{} sh -c 'echo {} $(xprop -notype -id {} _NET_WM_DESKTOP WM_NAME  \
          | sed "s#WM_NAME = \"# #g" | sed "s#\" WM_CLASS =# #g" \
          | sed "s#WM_CLASS = # #g" | sed "s#_NET_WM_DESKTOP =# #g" \
          | sed "s#\"# #g"  )' sh | rofi -dmenu -p "window" | awk '{print $1}' | xargs -I{} bspc node {} --to-desktop newest;  bspc node --focus {} 
}

files() {

  CURRENT="$HOME"

  while [ -n "$CURRENT" ]; do
    
    LL="$(find "$CURRENT" -maxdepth 1 \
        -not -path "$CURRENT" \
        -not -name '.*' \
        -printf '%P\n' | \
        sort)"
    [ "$CURRENT" != "/" ] && LL=".\n..\n$LL"

    CUR="$CURRENT"
    [ "$(echo "$CUR" | wc -m)" -gt 32 ] && \
      CUR="$(echo "$CUR" | awk -F/ '{for (i=1;i<NF;i++) \
          $i=substr($i,1,1+($i~/^[.]/))} 1' OFS=/)"

    SEL="$(echo "$LL" |
      rofi -dmenu -p "$CUR" -i \
      -columns 1)"

    [ -z "$SEL" ] && return

    CURRENT="$(realpath "$CURRENT/$SEL")"

    if [ "$SEL" = "." ]; then
      "$FILEMGR" "$CURRENT" &
      return
    elif [ "$SEL" != ".." ] && ! [ -d "$CURRENT" ]; then
      xdg-open "$CURRENT" &
      return
    fi

  done

}

character() {

  # Unicode Emoji generation script:
  # curl https://unicode.org/Public/emoji/15.0/emoji-test.txt | \
  #   awk '
  #     /^# group/ {
  #       g=tolower($3);
  #     }
  #     /^# subgroup/ {
  #       sg=tolower($3);
  #     }
  #     /; fully-qualified/ {
  #       gsub(/^.*fully-qualified\s+#\s+/,"",$0);
  #       $2="";
  #       emote=$1;
  #       $1="";
  #       gsub(/(^\s*)|:|,|\./,"",$0);
  #       gsub(/\s+/,"-",$0);
  #       print emote "\t" g "/" sg "/" tolower($0);
  #     }'

  CHARACTER_FILE="$HOME/.cache/characters.txt"

  [ -f "$CHARACTER_FILE" ] || \
    error "Character list file '$CHARACTER_FILE' is missing!" fatal 2

  SEL="$(
    rofi -dmenu -p 'character' -i \
    -columns 3 \
		-icon-theme -font "Twitter Color Emoji 11" < "$CHARACTER_FILE"
  )"

  if [ -n "$SEL" ]; then

    CHAR="$(echo "$SEL" | cut -f1)"

    printf '%s' "$CHAR" | xdotool type "$CHAR"
    printf '%s' "$CHAR" | xclip -selection clipboard

  fi

}

. "$WMRC_MODULES/init"
