#! /bin/bash
# DEPENDENCIES: xset, xidlehook

MODULES=$(realpath "$(dirname $0)/../")

# Time in seconds
BLANK_TIMEOUT=300
LOCK_TIMEOUT=305

function start() {
	
	xset s off -dpms

	nohup xidlehook \
		--not-when-fullscreen \
		--not-when-audio \
		--timer $BLANK_TIMEOUT \
			"xset dpms force off" '' \
		--timer $LOCK_TIMEOUT \
			"$MODULES/system/lock" '' \
		&>/dev/null&
		
}

function stop() {
	killall -u $(whoami) -9 xidlehook &> /dev/null
}

function restart() {
	if ! [ -z "$(pgrep -u $USER xidlehook)" ]; then
		stop
		start
	fi
}

if [ -z "$1" ]; then
	start
else
	$1
fi
