#!/bin/bash

MODULES=$(realpath "$(dirname $0)/../")

BCK_IMG="$HOME/Pictures/lockscreen.png"
if ! [ -f $BCK_IMG ]; then
    $MODULES/interface/notify error "Lockscreen image:\n<i>'lockscreen.png'</i> is missing from <i>'Pictures'</i> directory!"
    exit 1
fi

CACHE_DIR="$HOME/.cache/i3lock/"
if ! [ -e $CACHE_DIR ]; then
    mkdir -p $CACHE_DIR
fi

MD5_BKG_IMG=$(md5sum $BCK_IMG | cut -c 1-16)
MD5_SCREEN_CONFIG=$(xrandr | md5sum - | cut -c 1-16)

OUTPUT_IMG="$CACHE_DIR""$MD5_SCREEN_CONFIG"."$MD5_BKG_IMG".png
OUTPUT_IMG_WIDTH=0
OUTPUT_IMG_HEIGHT=0

I3LOCK_CMD="i3lock -u -i $OUTPUT_IMG -t -e"

if ! [ $(which convert) ]; then
    $MODULES/interface/notify error "ImageMagick is required dependency to generate screen-specific lockscreen image!"
    exit 1
fi

PARAMS=""

function individual_screen_images() {

    while read _ SCREEN_WIDTH SCREEN_HEIGHT SCREEN_X SCREEN_Y SCREEN_ROT _; do

        # ANGLE=0
        # case $SCREEN_ROT in
        #     left)
        #         ANGLE=270;;
        #     right)
        #         ANGLE=90;;
        #     inverted)
        #         ANGLE=180;;
        # esac

        # CACHE_IMG="$CACHE_DIR""$SCREEN_WIDTH"x"$SCREEN_HEIGHT"."$MD5_BKG_IMG"."$SCREEN_ROT".png
        CACHE_IMG="$CACHE_DIR""$SCREEN_WIDTH"x"$SCREEN_HEIGHT"."$MD5_BKG_IMG".png

        if ! [ -e $CACHE_IMG ]; then
            eval convert '$BCK_IMG' '-resize' '${SCREEN_WIDTH}X${SCREEN_HEIGHT}^' \
                         '-gravity' 'Center' '-crop' '${SCREEN_WIDTH}X${SCREEN_HEIGHT}+0+0' \
                         '+repage' '$CACHE_IMG'
                         # '-rotate $ANGLE' '+repage' '$CACHE_IMG'
        fi

        if (( $OUTPUT_IMG_WIDTH < $SCREEN_WIDTH+$SCREEN_X )); then
            OUTPUT_IMG_WIDTH=$(($SCREEN_WIDTH+$SCREEN_X))
        fi

        if (( $OUTPUT_IMG_HEIGHT < $SCREEN_HEIGHT+$SCREEN_Y )); then
            OUTPUT_IMG_HEIGHT=$(( $SCREEN_HEIGHT+$SCREEN_Y ))
        fi

        PARAMS="$PARAMS $CACHE_IMG -geometry +$SCREEN_X+$SCREEN_Y -composite "

    done <<< "$($MODULES/screen/export_layout)"

}

function composite_image() {

    individual_screen_images

    eval convert -size ${OUTPUT_IMG_WIDTH}x${OUTPUT_IMG_HEIGHT} "xc:#212221" "$OUTPUT_IMG"
    eval convert "$OUTPUT_IMG" "$PARAMS" "$OUTPUT_IMG"

}

function lock_screen() {

    if ! [ -e $OUTPUT_IMG ]; then
        composite_image
    fi

    $I3LOCK_CMD "$1"

}

if [ "$1" == "generate" ]; then
    composite_image
else
    if [ "$1" = "-n" ]; then
        WAIT=$(lock_screen)
    else
        lock_screen
    fi
fi