#! /bin/bash
# RC_ASYNC_LOCK

MODULES=$(realpath "$(dirname $0)/../")
BSPWMRC=$(realpath "$(dirname $0)/../../")/bspwmrc

DIR=$(dirname "$0")
SCRNLYTS="$HOME/.screenlayout"
mkdir -p "$SCRNLYTS"

MONITORS=`xrandr --query | grep " connected" | cut -d " " -f 1 | sort`
CUSTOM=`find $SCRNLYTS -type f -not -name ".restore.sh" -printf "%P\n" | sed "s/.sh//" | sort`
if [ -f "$SCRNLYTS/.restore.sh" ]; then
	CUSTOM="$CUSTOM"
fi
LIST="Configure new layout using arandr\nApply last used layout\n$CUSTOM\n$MONITORS\n"

if [ -z "$1" ]; then

	ROFI="rofi -dmenu -i -theme Arc-Dark -width 20 -lines `printf "$LIST" | wc -l`"
	SELECTED=`printf "$LIST" | $ROFI -p "Monitor layout"`

	if [ "$SELECTED" == "Apply last used layout" ]; then

		SELECTED=".restore"
		CUSTOM=".restore\n$CUSTOM"

	elif [ "$SELECTED" == "Configure new layout using arandr" ]; then

		MD5_BEFORE=$(xrandr | md5sum - | cut -c 1-16)
		WAIT=$(arandr)
		MD5_AFTER=$(xrandr | md5sum - | cut -c 1-16)

		if [ "$MD5_BEFORE" != "$MD5_AFTER" ]; then
			$MODULES/interface/notify info "Custom monitor layout applied successfully!"
			$BSPWMRC reload
		fi

		exit

	fi

elif [[ $LIST == *"$1"* ]]; then

	SELECTED="$1"

else

	$MODULES/interface/notify error "Layout '<i>$1</i>' does not exist"
	exit 1

fi

MD5_BEFORE=$(xrandr | md5sum - | cut -c 1-16)

if [ -z "$SELECTED" ]; then

	exit

elif [[ "$CUSTOM\n$MONITORS" == *"$SELECTED"* ]]; then

	WAIT=$(sh "$SCRNLYTS/$SELECTED.sh")

else

	OUTPUT="xrandr"

	for M in $MONITORS; do

		if [[ "$SELECTED" == "$M" ]]; then
			RES=`xrandr --query | grep -A 1 $M | tail -n 1 | egrep -o "[0-9]+x[0-9]+"`
			OUTPUT="$OUTPUT --output $M --primary --mode $RES --pos 0x0 --rotate normal"
		else
			OUTPUT="$OUTPUT --output $M --off"
		fi

	done

	WAIT=$("$OUTPUT")

fi

MD5_AFTER=$(xrandr | md5sum - | cut -c 1-16)

if  [ "$MD5_BEFORE" != "$MD5_AFTER" ]; then

	if [ "$SELECTED" == ".restore" ]; then
		$MODULES/interface/notify info "Monitor layout restored successfully!";
	else
		$MODULES/interface/notify info "Monitor layout changed to '<i>$SELECTED</i>' successfully!";
	fi

	$MODULES/screen/export_layout xrandr > "$SCRNLYTS/.restore.sh"
	$BSPWMRC reload
fi