#! /bin/sh
# DEPENDENCIES: feh

MODULES=$(realpath "$(dirname $0)/../")

if [ ! -f $HOME/Pictures/wallpaper.png ]; then
	$MODULES/interface/notify warning "Unable to set wallpaper:\n<i>'wallpaper.png'</i> is missing from <i>'Pictures'</i> directory!"
else
	DISPLAY=$DISPLAY feh --bg-fill $HOME/Pictures/wallpaper.png
fi
