#!/bin/sh

export WMRC_DEPENDENCIES='pgrep'

APPS='unclutter -idle 1
      redshift-qt
      libinput-gestures-setup start
      xhost +si:localuser:$USER
      snixembed --fork
      keepassxc
      kdeconnect-indicator
      flameshot
      thunderbird
      signal-desktop --start-in-tray
      dino --gapplication-service
      safeeyes
      gromit-mpx
      blueman-applet
      openrgb -c ff6f00 -b 10
      '

app_list() {

  APPLIST=""

  if [ -n "$2" ]; then

    for A in $(echo "$*" | sed "s/$1//g"); do

      APPLIST="$APPLIST\n$(echo "$APPS" |
              grep -P "^ *$A( |$)" ||
              warn "Application not listed" "$A"
      )"

    done

  else

    APPLIST="$APPS"

  fi

}

start() {

  local CMD
  local EXE

  app_list "$@"

  for A in $(echo "$APPLIST" | sed 's/^ *//g; s/ /\&nbsp/g'); do

    CMD="$(echo "$A" | sed 's/\&nbsp/ /g')"
    EXE="$(echo "$CMD" | cut -d' ' -f1)"

    if [ -n "$(command -v "$EXE")" ]; then
      if pgrep -u "$(whoami)" "$EXE" >/dev/null; then
        warn "Application already running" "$EXE"
        continue
      else
        info "Starting application" "$EXE"
        $CMD >/dev/null 2>&1 &
      fi
    else
      warn "Application not installed" "$EXE"
    fi

  done

}

stop() {

  local EXE

  app_list "$@"

  for A in $(echo "$APPLIST" | sed 's/^ *//g; s/ /\&nbsp/g'); do

    EXE="$(echo "$A" | sed 's/\&nbsp/ /g' | cut -d' ' -f1)"

    if pgrep -u "$(whoami)" "$EXE" >/dev/null; then
      killall -u "$(whoami)" -9 "$EXE" &
    else
      warn "Application not running" "$EXE"
      continue
    fi

  done

}
