#!/bin/sh

export WMRC_DEPENDENCIES='dunst pgrep'
export WMRC_LIBRARIES='notify'

start() {
    if daemon_get_pid; then
        error "Dunst notification server is already running!"
        return 1
    fi
    dunst &
    daemon_set_pid "$!"
}

pause() {
    if daemon_get_pid; then
        info "Notifications paused"
        kill -USR1 "$DAEMON_PID"
    else
        warn "Dunst notification server is not running!"
    fi
}

resume() {
    if daemon_get_pid; then
        info "Notifications resumed"
        kill -USR2 "$DAEMON_PID"
    else
        warn "Dunst notification server is not running!"
    fi
}

daemon_get_pid() {
    _other_pid="$(pgrep -u "$USER" -o dunst)"
    if ! test -f "$_pid_file" || ! kill -0 "$(cat "$_pid_file")" >/dev/null 2>/dev/null; then
        debug 'Daemon spawned by wmrc is not running'
        if [ -n "$_other_pid" ]; then
            DAEMON_PID="$_other_pid"
            debug 'Found daemon pid' "$DAEMON_PID"
        else
            return 1
        fi
    else
        DAEMON_PID="$(cat "$_pid_file")"
        debug 'Get daemon pid' "$DAEMON_PID"
    fi
}
