#!/bin/sh

export WMRC_DEPENDENCIES='x0vncserver pgrep'

start() {
  if ! [ -f "$HOME/.vnc/passwd" ]; then
    error "Password for VNC server is not set!"
    return 1
  fi
  if daemon_get_pid; then
		error "VNC server is already running!"
		return 1
	fi
  x0vncserver -CompareFB=1 -FrameRate=24 -SecurityTypes=TLSVnc \
    --PasswordFile="$HOME/.vnc/passwd" >/dev/null &
  daemon_set_pid "$!"
}
